# Generated by Django 2.2.5 on 2020-02-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlutenTestLog',
            fields=[
                ('transaction_num', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('participant_id', models.CharField(max_length=100)),
                ('inspection_result', models.CharField(max_length=100)),
                ('scanned_result', models.CharField(max_length=100)),
                ('visualization_method', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wrap',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('gluten_free_flag', models.BooleanField()),
                ('label_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glutentest.GlutenTestLog')),
            ],
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glutentest.Wrap'),
        ),
    ]
