# Generated by Django 2.2.5 on 2020-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrap',
            name='label_language',
            field=models.CharField(choices=[('EN', 'English'), ('RUS', 'Russian'), ('N', 'No label')], max_length=100),
        ),
    ]
