# Generated by Django 2.2.5 on 2020-02-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0003_glutentestlog_trust_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrap',
            name='label_language',
            field=models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('No label', 'No label')], max_length=100),
        ),
    ]
