# Generated by Django 2.2.5 on 2020-02-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0004_auto_20200207_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glutentestlog',
            name='sample',
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='label_language',
            field=models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('No label', 'No label')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='sample_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glutentestlog',
            name='inspection_result',
            field=models.BooleanField(max_length=100),
        ),
        migrations.AlterField(
            model_name='glutentestlog',
            name='probability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='glutentestlog',
            name='trust_flag',
            field=models.BooleanField(null=True),
        ),
    ]
