# Generated by Django 2.2.5 on 2020-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0005_auto_20200212_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glutentestlog',
            name='inspection_result',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='glutentestlog',
            name='scanned_result',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
