# Generated by Django 2.2.5 on 2020-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0006_auto_20200212_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutentestlog',
            name='session',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
