# Generated by Django 2.2.5 on 2020-02-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0007_glutentestlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='glutentestlog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
