# Generated by Django 2.2.5 on 2020-02-16 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0008_glutentestlog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glutentestlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='feedback_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='inspected_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='scanned_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
