# Generated by Django 2.2.5 on 2020-02-16 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glutentest', '0009_auto_20200217_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glutentestlog',
            name='start_time',
        ),
        migrations.AddField(
            model_name='glutentestlog',
            name='started_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 23, 29, 39, 878616)),
            preserve_default=False,
        ),
    ]
