# Generated by Django 2.2.5 on 2019-11-24 06:11

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbiNIRSApp',
            fields=[
                ('app_id', models.IntegerField(default=dashboard.models.id_generator, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='appname')),
                ('app_displayname', models.CharField(default='', max_length=1024, verbose_name='App Name')),
                ('app_description', models.TextField(default='')),
                ('app_version', models.CharField(default='', max_length=1024)),
                ('app_icon', models.CharField(default='', max_length=65535)),
                ('app_thumbnail', models.CharField(default='', max_length=65535)),
                ('app_classes', models.TextField(default='', editable=False)),
                ('app_visits', models.IntegerField(default=0)),
                ('app_created_at', models.DateTimeField(auto_now_add=True)),
                ('app_updated_at', models.DateTimeField(auto_now=True)),
                ('app_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppTestLog',
            fields=[
                ('test_transaction_number', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('test_result', models.CharField(default='', editable=False, max_length=64)),
                ('test_device_id', models.CharField(editable=False, max_length=64, null=True)),
                ('test_feedback', models.BooleanField(editable=False)),
                ('test_filename', models.CharField(editable=False, max_length=1024)),
                ('test_created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.UbiNIRSApp')),
            ],
        ),
        migrations.CreateModel(
            name='AppSpectrumLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1024)),
                ('description', models.TextField(null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UbiNIRSApp')),
            ],
        ),
        migrations.CreateModel(
            name='AppSpectrumFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=100000, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.UbiNIRSApp')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.AppSpectrumLabel')),
            ],
        ),
    ]
