# Generated by Django 2.2.5 on 2019-11-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191124_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appspectrumfile',
            name='app',
        ),
    ]
