# Generated by Django 2.2.5 on 2019-11-24 06:47

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_appspectrumfile_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appspectrumfile',
            name='file',
            field=models.FileField(max_length=100000, upload_to=dashboard.models.get_reference_file_path),
        ),
    ]
