# Generated by Django 2.2.5 on 2019-11-24 09:49

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191124_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appspectrumfile',
            name='file',
            field=models.FileField(max_length=100000, upload_to=dashboard.models.get_reference_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='appspectrumfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
