# Generated by Django 2.2.5 on 2020-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191124_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptestlog',
            name='test_note',
            field=models.TextField(default='', null=True),
        ),
    ]
